# Numpy

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [1]:
import numpy as np

In [8]:
arr = np.array([1,2])


array([1, 2])

In [25]:
print(arr)
print(type(arr))
print(arr.shape)
print(arr.size)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
(2, 2)
4


In [21]:
arr2 = np.array([[1,2],[3,4]])

In [22]:
print(arr2)
print(type(arr2))
print(arr2.shape)
print(arr2.size)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
(2, 2)
4


### Specifing the type of array element

In [30]:
arr = np.array([1,2], dtype = np.float32)
type(arr[0])

numpy.float32

### Built in function

In [32]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
arr = np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
arr = np.random.random((4,4))
arr

array([[0.64566604, 0.732806  , 0.59128442, 0.08123343],
       [0.55030302, 0.52621809, 0.7323482 , 0.95873526],
       [0.15742325, 0.4695066 , 0.07213976, 0.03643818],
       [0.39019041, 0.28440733, 0.43464351, 0.32966848]])

In [35]:
arr = np.full((4,4),6)
arr

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

### Reshaping an array

In [39]:
arr.reshape(2,2,4)

array([[[6, 6, 6, 6],
        [6, 6, 6, 6]],

       [[6, 6, 6, 6],
        [6, 6, 6, 6]]])

### Flatten an array

In [42]:
arr = np.random.random((2,4))
arr

array([[[0.25733182, 0.91842342, 0.79245161, 0.33344026],
        [0.56120275, 0.140601  , 0.40293324, 0.6546494 ]],

       [[0.27376999, 0.55084871, 0.78847892, 0.34801832],
        [0.05587256, 0.83345059, 0.55381225, 0.68130417]]])

In [43]:
arr.flatten()

array([0.25733182, 0.91842342, 0.79245161, 0.33344026, 0.56120275,
       0.140601  , 0.40293324, 0.6546494 , 0.27376999, 0.55084871,
       0.78847892, 0.34801832, 0.05587256, 0.83345059, 0.55381225,
       0.68130417])

# Operators

### Unary Operator

In [46]:
arr = np.array([[1,2,3],
                [4,5,6]])
print(arr.min())  # finding min
print(arr.max())  # finding max
print(arr.sum())  # finding sum

1
6
21


### Binary operators

In [52]:
arr1 = np.array([1,2])
arr2 = np.array([3,4])
print(arr1 + arr2) #sum of two array elementwise
print(arr1 * arr2) #multiply of two array elementwise
print(arr1.dot(arr2)) #sum of two array elementwise

[4 6]
[3 8]
11


## Matrix Multiplication

In [53]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[2,4],[4,4]])
np.matmul(m1,m2)

array([[10, 12],
       [22, 28]])

## Sorting array

In [57]:
arr = np.random.random((4,3))
arr

array([[0.61689135, 0.56565123, 0.13210023],
       [0.03781895, 0.80387286, 0.79622114],
       [0.76759139, 0.52011227, 0.32178257],
       [0.74365204, 0.85219516, 0.47626977]])

In [59]:
np.sort(arr, axis = 1)

array([[0.13210023, 0.56565123, 0.61689135],
       [0.03781895, 0.79622114, 0.80387286],
       [0.32178257, 0.52011227, 0.76759139],
       [0.47626977, 0.74365204, 0.85219516]])

In [60]:
np.sort(arr, axis = 0)

array([[0.03781895, 0.52011227, 0.13210023],
       [0.61689135, 0.56565123, 0.32178257],
       [0.74365204, 0.80387286, 0.47626977],
       [0.76759139, 0.85219516, 0.79622114]])